# Generated by Django 4.0.6 on 2022-07-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviamento',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, max_length=18, null=True)),
                ('produto', models.CharField(blank=True, max_length=18, null=True)),
                ('nome', models.CharField(blank=True, max_length=18, null=True)),
                ('categoria', models.CharField(blank=True, max_length=18, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=18, null=True)),
                ('valor', models.FloatField(blank=True, max_length=18, null=True)),
                ('data_aquisicao', models.DateField(blank=True, max_length=18, null=True)),
                ('quantidade', models.IntegerField(blank=True, max_length=18, null=True)),
                ('descricao', models.TextField(blank=True, max_length=18, null=True)),
                ('marca', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=18, null=True)),
                ('numero_maquinario', models.IntegerField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_maquinario', models.IntegerField(blank=True, max_length=18, null=True)),
                ('nome', models.CharField(blank=True, max_length=18, null=True)),
                ('data_envio', models.DateField(blank=True, max_length=18, null=True)),
                ('provavel_retorno', models.DateField(blank=True, max_length=18, null=True)),
                ('motivo', models.CharField(blank=True, max_length=18, null=True)),
                ('prestador_servico', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, max_length=180, null=True)),
                ('nome', models.CharField(blank=True, max_length=180, null=True)),
                ('modelo', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(blank=True, max_length=180, null=True)),
                ('valor', models.FloatField(blank=True, max_length=180, null=True)),
                ('descricao', models.TextField(blank=True, max_length=180, null=True)),
                ('data_aquisicao', models.DateField(blank=True, max_length=180, null=True)),
                ('tipo', models.BooleanField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(blank=True, max_length=180, null=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=180, null=True)),
                ('cpf', models.IntegerField(blank=True, max_length=180, null=True)),
                ('telefone', models.IntegerField(blank=True, max_length=180, null=True)),
                ('funcao_operador', models.CharField(blank=True, max_length=180, null=True)),
                ('whatsapp', models.IntegerField(blank=True, max_length=180, null=True)),
                ('email', models.EmailField(blank=True, max_length=180, null=True)),
                ('endereco', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('tempo_execucao', models.TimeField(blank=True, max_length=18, null=True)),
                ('aviamento_utilizado', models.CharField(blank=True, max_length=18, null=True)),
                ('maquinario_alocado', models.CharField(blank=True, max_length=18, null=True)),
                ('operador_alocado', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
    ]
