# Generated by Django 4.0.6 on 2022-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idk', models.BigAutoField(primary_key=True, serialize=False)),
                ('path_img_perfil', models.ImageField(blank=True, null=True, upload_to='img/pessoal/')),
                ('nome_log', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_ten', models.CharField(blank=True, max_length=310, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='categoria',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='produto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviamento',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='numero_maquinario',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='numero_maquinario',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='prestador_servico',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='provavel_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='modelo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='tipo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='funcao_operador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='aviamento_utilizado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='maquinario_alocado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='operador_alocado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tempo_execucao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
