# Generated by Django 4.0.6 on 2022-07-17 13:33

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario_alter_aviamento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='nome',
            field=models.ForeignKey(blank=True, db_column='nome', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome2', to='main.maquinario', verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='numero_maquinario',
            field=models.ForeignKey(blank=True, db_column='numero_maquinario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero2', to='main.maquinario', verbose_name='Número Maquinário'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='nome',
            field=models.ForeignKey(blank=True, db_column='nome', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome1', to='main.maquinario', verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='numero_maquinario',
            field=models.ForeignKey(blank=True, db_column='numero_maquinario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero1', to='main.maquinario', verbose_name='Número Maquinário'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[main.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='processo',
            name='aviamento_utilizado',
            field=models.ForeignKey(blank=True, db_column='aviamento_utilizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome1', to='main.aviamento', verbose_name='Aviamento Utilizado'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='maquinario_alocado',
            field=models.ForeignKey(blank=True, db_column='maquinario_alocado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome3', to='main.maquinario', verbose_name='Maquinário Alocado'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='operador_alocado',
            field=models.ForeignKey(blank=True, db_column='operador_alocado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_completo1', to='main.operador', verbose_name='Operador Alocado'),
        ),
    ]
