# Generated by Django 4.0.6 on 2022-07-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_baixa_nome_alter_baixa_numero_maquinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinario',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='aviamento_utilizado',
            field=models.ForeignKey(blank=True, db_column='aviamento_utilizado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome1', to='main.aviamento', verbose_name='Aviamento Utilizado'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='operador_alocado',
            field=models.ForeignKey(blank=True, db_column='operador_alocado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_completo1', to='main.operador', verbose_name='Operador Alocado'),
        ),
    ]
