# Generated by Django 4.0.6 on 2022-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_maquinario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
