# Generated by Django 4.0.6 on 2022-07-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_processo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baixa',
            name='numero_maquinario',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='numero_maquinario',
        ),
        migrations.AddField(
            model_name='baixa',
            name='numero',
            field=models.ForeignKey(blank=True, db_column='numero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero2', to='main.maquinario', verbose_name='Número Maquinário'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='numero',
            field=models.ForeignKey(blank=True, db_column='numero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero1', to='main.maquinario', verbose_name='Número Maquinário'),
        ),
    ]
